/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waterfairy_tool_jni_MyJni */

#ifndef _Included_com_waterfairy_tool_jni_MyJni
#define _Included_com_waterfairy_tool_jni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waterfairy_tool_jni_MyJni
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_waterfairy_tool_jni_MyJni_sayHello
  (JNIEnv *env, jclass jobj){
    return (*env)->NewStringUTF(env,"jni hafdafd");
  }

#ifdef __cplusplus
}
#endif
#endif
